apiVersion: v1
kind: Service
metadata:
  name: terraform-parse
  labels:
    app: terraform-parse
spec:
  type: {{ .Values.service.type }}
  selector:
    app: terraform-parse
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
